<?php

use Carbon\Carbon as Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MaterialTypeTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * Sample query (needs improvement):

        SELECT t1.name AS lev1, t2.name as lev2, t3.name as lev3, t4.name as lev4, t5.name as lev5
        FROM material_types AS t1
        LEFT JOIN material_types AS t2 ON t2.parent_id = t1.id
        LEFT JOIN material_types AS t3 ON t3.parent_id = t2.id
        LEFT JOIN material_types AS t4 ON t4.parent_id = t3.id
        LEFT JOIN material_types AS t5 ON t5.parent_id = t4.id
        WHERE t1.id = 100
        ORDER BY t1.id, t2.id, t3.id, t4.id, t5.id;

     *
     * @return void
     */
    public function run()
    {
        if (DB::connection()->getDriverName() == 'mysql') {
            DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        }

        DB::table('material_types')->truncate();

        $now = Carbon::now();
        
        $material_types = [
            [
                'id' => 1,
                'parent_id' => null,
                'name' => 'Primitive',
                'concatenated_name' => 'Primitive',
                'rgb_r' => 255,
                'rgb_g' => 255,
                'rgb_b' => 255,
                'old_recipe_type_id' => null,
                'old_material_type_id' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            [
                'id' => 5,
                'parent_id' => 1,
                'name' => 'Alumina',
                'concatenated_name' => 'Alumina',
                'rgb_r' => 255,
                'rgb_g' => 255,
                'rgb_b' => 255,
                'old_recipe_type_id' => null,
                'old_material_type_id' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            [
                'id' => 9,
                'parent_id' => 1,
                'name' => 'Ash',
                'concatenated_name' => 'Ash',
                'rgb_r' => 255,
                'rgb_g' => 255,
                'rgb_b' => 255,
                'old_recipe_type_id' => null,
                'old_material_type_id' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ],


            [
                'id' => 13,
                'parent_id' => 1,
                'name' => 'Clay',
                'concatenated_name' => 'Clay',
                'rgb_r' => 255,
                'rgb_g' => 255,
                'rgb_b' => 255,
                'old_recipe_type_id' => null,
                'old_material_type_id' => 3,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            [
                'id' => 17,
                'parent_id' => 1,
                'name' => 'Colorant',
                'concatenated_name' => 'Colorant',
                'rgb_r' => 255,
                'rgb_g' => 255,
                'rgb_b' => 255,
                'old_recipe_type_id' => null,
                'old_material_type_id' => 4,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            [
                'id' => 20,
                'parent_id' => 1,
                'name' => 'Feldspar',
                'concatenated_name' => 'Feldspar',
                'rgb_r' => 255,
                'rgb_g' => 255,
                'rgb_b' => 255,
                'old_recipe_type_id' => null,
                'old_material_type_id' => 5,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            [
                'id' => 23,
                'parent_id' => 1,
                'name' => 'Flux',
                'concatenated_name' => 'Flux',
                'rgb_r' => 255,
                'rgb_g' => 255,
                'rgb_b' => 255,
                'old_recipe_type_id' => null,
                'old_material_type_id' => 6,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            [
                'id' => 26,
                'parent_id' => 1,
                'name' => 'Frit',
                'concatenated_name' => 'Frit',
                'rgb_r' => 255,
                'rgb_g' => 255,
                'rgb_b' => 255,
                'old_recipe_type_id' => null,
                'old_material_type_id' => 7,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            [
                'id' => 29,
                'parent_id' => 1,
                'name' => 'Opacifier',
                'concatenated_name' => 'Opacifier',
                'rgb_r' => 255,
                'rgb_g' => 255,
                'rgb_b' => 255,
                'old_recipe_type_id' => null,
                'old_material_type_id' => 9,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            [
                'id' => 32,
                'parent_id' => 1,
                'name' => 'Silica',
                'concatenated_name' => 'Silica',
                'rgb_r' => 255,
                'rgb_g' => 255,
                'rgb_b' => 255,
                'old_recipe_type_id' => null,
                'old_material_type_id' => 10,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            [
                'id' => 35,
                'parent_id' => 1,
                'name' => 'Miscellaneous',
                'concatenated_name' => 'Miscellaneous',
                'rgb_r' => 255,
                'rgb_g' => 255,
                'rgb_b' => 255,
                'old_recipe_type_id' => null,
                'old_material_type_id' => 8,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // COMPOSITE TYPES (GLAZES, etc.)
            [
                'id' => 100,
                'parent_id' => null,
                'name' => 'Composite',
                'concatenated_name' => 'Composite',
                'rgb_r' => 255,
                'rgb_g' => 255,
                'rgb_b' => 255,
                'old_recipe_type_id' => null,
                'old_material_type_id' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            [
                'id' => 110,
                'parent_id' => 100,
                'name' => 'Clay Body',
                'concatenated_name' => 'Clay Body',
                'rgb_r' => 255,
                'rgb_g' => 255,
                'rgb_b' => 255,
                'old_recipe_type_id' => 1,
                'old_material_type_id' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            [
                'id' => 120,
                'parent_id' => 110,
                'name' => 'Earthenware',
                'concatenated_name' => 'Earthenware',
                'rgb_r' => 205,
                'rgb_g' => 51,
                'rgb_b' => 51,
                'old_recipe_type_id' => 2,
                'old_material_type_id' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            [
                'id' => 130,
                'parent_id' => 120,
                'name' => 'Throwing',
                'concatenated_name' => 'Earthenware - Throwing',
                'rgb_r' => 205,
                'rgb_g' => 51,
                'rgb_b' => 51,
                'old_recipe_type_id' => 3,
                'old_material_type_id' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            [
                'id' => 140,
                'parent_id' => 120,
                'name' => 'Slipcasting',
                'concatenated_name' => 'Earthenware - Slipcasting',
                'rgb_r' => 205,
                'rgb_g' => 51,
                'rgb_b' => 51,
                'old_recipe_type_id' => 4,
                'old_material_type_id' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            [
                'id' => 150,
                'parent_id' => 120,
                'name' => 'Sculpture',
                'concatenated_name' => 'Earthenware - Sculpture',
                'rgb_r' => 205,
                'rgb_g' => 51,
                'rgb_b' => 51,
                'old_recipe_type_id' => 5,
                'old_material_type_id' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            [
                'id' => 160,
                'parent_id' => 120,
                'name' => 'Hand-building',
                'concatenated_name' => 'Earthenware - Hand-building',
                'rgb_r' => 205,
                'rgb_g' => 51,
                'rgb_b' => 51,
                'old_recipe_type_id' => 6,
                'old_material_type_id' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            [
                'id' => 170,
                'parent_id' => 120,
                'name' => 'Salt',
                'concatenated_name' => 'Earthenware - Salt',
                'rgb_r' => 205,
                'rgb_g' => 51,
                'rgb_b' => 51,
                'old_recipe_type_id' => 7,
                'old_material_type_id' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            [
                'id' => 180,
                'parent_id' => 120,
                'name' => 'Raku',
                'concatenated_name' => 'Earthenware - Raku',
                'rgb_r' => 205,
                'rgb_g' => 51,
                'rgb_b' => 51,
                'old_recipe_type_id' => 8,
                'old_material_type_id' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            [
                'id' => 190,
                'parent_id' => 110,
                'name' => 'Stoneware',
                'concatenated_name' => 'Stoneware',
                'rgb_r' => 139,
                'rgb_g' => 35,
                'rgb_b' => 35,
                'old_recipe_type_id' => 9,
                'old_material_type_id' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            [
                'id' => 200,
                'parent_id' => 190,
                'name' => 'Throwing',
                'concatenated_name' => 'Stoneware - Throwing',
                'rgb_r' => 139,
                'rgb_g' => 35,
                'rgb_b' => 35,
                'old_recipe_type_id' => 10,
                'old_material_type_id' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            [
                'id' => 210,
                'parent_id' => 190,
                'name' => 'Slipcasting',
                'concatenated_name' => 'Stoneware - Slipcasting',
                'rgb_r' => 139,
                'rgb_g' => 35,
                'rgb_b' => 35,
                'old_recipe_type_id' => 11,
                'old_material_type_id' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            [
                'id' => 220,
                'parent_id' => 190,
                'name' => 'Sculpture',
                'concatenated_name' => 'Stoneware - Sculpture',
                'rgb_r' => 139,
                'rgb_g' => 35,
                'rgb_b' => 35,
                'old_recipe_type_id' => 12,
                'old_material_type_id' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            [
                'id' => 230,
                'parent_id' => 190,
                'name' => 'Hand-building',
                'concatenated_name' => 'Stoneware - Hand-building',
                'rgb_r' => 139,
                'rgb_g' => 35,
                'rgb_b' => 35,
                'old_recipe_type_id' => 13,
                'old_material_type_id' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            [
                'id' => 240,
                'parent_id' => 190,
                'name' => 'Salt',
                'concatenated_name' => 'Stoneware - Salt',
                'rgb_r' => 139,
                'rgb_g' => 35,
                'rgb_b' => 35,
                'old_recipe_type_id' => 14,
                'old_material_type_id' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            [
                'id' => 250,
                'parent_id' => 190,
                'name' => 'Raku',
                'concatenated_name' => 'Stoneware - Raku',
                'rgb_r' => 139,
                'rgb_g' => 35,
                'rgb_b' => 35,
                'old_recipe_type_id' => 15,
                'old_material_type_id' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            [
                'id' => 260,
                'parent_id' => 110,
                'name' => 'Porcelain',
                'concatenated_name' => 'Porcelain',
                'rgb_r' => 255,
                'rgb_g' => 255,
                'rgb_b' => 240,
                'old_recipe_type_id' => 16,
                'old_material_type_id' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            [
                'id' => 270,
                'parent_id' => 260,
                'name' => 'Throwing',
                'concatenated_name' => 'Porcelain - Throwing',
                'rgb_r' => 255,
                'rgb_g' => 255,
                'rgb_b' => 240,
                'old_recipe_type_id' => 17,
                'old_material_type_id' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            [
                'id' => 280,
                'parent_id' => 260,
                'name' => 'Slipcasting',
                'concatenated_name' => 'Porcelain - Slipcasting',
                'rgb_r' => 255,
                'rgb_g' => 255,
                'rgb_b' => 240,
                'old_recipe_type_id' => 18,
                'old_material_type_id' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            [
                'id' => 290,
                'parent_id' => 260,
                'name' => 'Sculpture',
                'concatenated_name' => 'Porcelain - Sculpture',
                'rgb_r' => 255,
                'rgb_g' => 255,
                'rgb_b' => 240,
                'old_recipe_type_id' => 19,
                'old_material_type_id' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            [
                'id' => 300,
                'parent_id' => 260,
                'name' => 'Hand-building',
                'concatenated_name' => 'Porcelain - Hand-building',
                'rgb_r' => 255,
                'rgb_g' => 255,
                'rgb_b' => 240,
                'old_recipe_type_id' => 20,
                'old_material_type_id' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            [
                'id' => 310,
                'parent_id' => 260,
                'name' => 'Salt',
                'concatenated_name' => 'Porcelain - Salt',
                'rgb_r' => 255,
                'rgb_g' => 255,
                'rgb_b' => 240,
                'old_recipe_type_id' => 21,
                'old_material_type_id' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            [
                'id' => 320,
                'parent_id' => 260,
                'name' => 'Raku',
                'concatenated_name' => 'Porcelain - Raku',
                'rgb_r' => 255,
                'rgb_g' => 255,
                'rgb_b' => 240,
                'old_recipe_type_id' => 22,
                'old_material_type_id' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            [
                'id' => 330,
                'parent_id' => 110,
                'name' => 'Flameware',
                'concatenated_name' => 'Flameware',
                'rgb_r' => 205,
                'rgb_g' => 38,
                'rgb_b' => 38,
                'old_recipe_type_id' => 23,
                'old_material_type_id' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            [
                'id' => 340,
                'parent_id' => 330,
                'name' => 'Throwing',
                'concatenated_name' => 'Flameware - Throwing',
                'rgb_r' => 205,
                'rgb_g' => 38,
                'rgb_b' => 38,
                'old_recipe_type_id' => 24,
                'old_material_type_id' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            [
                'id' => 350,
                'parent_id' => 330,
                'name' => 'Slipcasting',
                'concatenated_name' => 'Flameware - Slipcasting',
                'rgb_r' => 205,
                'rgb_g' => 38,
                'rgb_b' => 38,
                'old_recipe_type_id' => 25,
                'old_material_type_id' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            [
                'id' => 360,
                'parent_id' => 330,
                'name' => 'Sculpture',
                'concatenated_name' => 'Flameware - Sculpture',
                'rgb_r' => 205,
                'rgb_g' => 38,
                'rgb_b' => 38,
                'old_recipe_type_id' => 26,
                'old_material_type_id' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            [
                'id' => 370,
                'parent_id' => 330,
                'name' => 'Hand-building',
                'concatenated_name' => 'Flameware - Hand-building',
                'rgb_r' => 205,
                'rgb_g' => 38,
                'rgb_b' => 38,
                'old_recipe_type_id' => 27,
                'old_material_type_id' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            [
                'id' => 380,
                'parent_id' => 330,
                'name' => 'Salt',
                'concatenated_name' => 'Flameware - Salt',
                'rgb_r' => 205,
                'rgb_g' => 38,
                'rgb_b' => 38,
                'old_recipe_type_id' => 28,
                'old_material_type_id' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            [
                'id' => 390,
                'parent_id' => 330,
                'name' => 'Raku',
                'concatenated_name' => 'Flameware - Raku',
                'rgb_r' => 205,
                'rgb_g' => 38,
                'rgb_b' => 38,
                'old_recipe_type_id' => 29,
                'old_material_type_id' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            [
                'id' => 400,
                'parent_id' => 100,
                'name' => 'Slip & Engobe',
                'concatenated_name' => 'Slip & Engobe',
                'rgb_r' => 255,
                'rgb_g' => 255,
                'rgb_b' => 255,
                'old_recipe_type_id' => 30,
                'old_material_type_id' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            [
                'id' => 410,
                'parent_id' => 400,
                'name' => 'Slip',
                'concatenated_name' => 'Slip',
                'rgb_r' => 255,
                'rgb_g' => 255,
                'rgb_b' => 255,
                'old_recipe_type_id' => 31,
                'old_material_type_id' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            [
                'id' => 420,
                'parent_id' => 400,
                'name' => 'Engobe',
                'concatenated_name' => 'Engobe',
                'rgb_r' => 255,
                'rgb_g' => 255,
                'rgb_b' => 255,
                'old_recipe_type_id' => 32,
                'old_material_type_id' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            [
                'id' => 430,
                'parent_id' => 400,
                'name' => 'Terra Sigillata',
                'concatenated_name' => 'Terra Sigillata',
                'rgb_r' => 255,
                'rgb_g' => 255,
                'rgb_b' => 255,
                'old_recipe_type_id' => 33,
                'old_material_type_id' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            [
                'id' => 440,
                'parent_id' => 100,
                'name' => 'Overglaze',
                'concatenated_name' => 'Overglaze',
                'rgb_r' => 255,
                'rgb_g' => 255,
                'rgb_b' => 255,
                'old_recipe_type_id' => 34,
                'old_material_type_id' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            [
                'id' => 450,
                'parent_id' => 100,
                'name' => 'Underglaze',
                'concatenated_name' => 'Underglaze',
                'rgb_r' => 255,
                'rgb_g' => 255,
                'rgb_b' => 255,
                'old_recipe_type_id' => 35,
                'old_material_type_id' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            [
                'id' => 460,
                'parent_id' => 100,
                'name' => 'Glaze',
                'concatenated_name' => 'Glaze',
                'rgb_r' => 255,
                'rgb_g' => 255,
                'rgb_b' => 255,
                'old_recipe_type_id' => 36,
                'old_material_type_id' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            [
                'id' => 470,
                'parent_id' => 460,
                'name' => 'Clear',
                'concatenated_name' => 'Clear',
                'rgb_r' => 255,
                'rgb_g' => 255,
                'rgb_b' => 255,
                'old_recipe_type_id' => 37,
                'old_material_type_id' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            [
                'id' => 480,
                'parent_id' => 460,
                'name' => 'White, Off-White',
                'concatenated_name' => 'White, Off-White',
                'rgb_r' => 255,
                'rgb_g' => 255,
                'rgb_b' => 255,
                'old_recipe_type_id' => 38,
                'old_material_type_id' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            [
                'id' => 490,
                'parent_id' => 460,
                'name' => 'Iron',
                'concatenated_name' => 'Iron',
                'rgb_r' => 143,
                'rgb_g' => 188,
                'rgb_b' => 143,
                'old_recipe_type_id' => 39,
                'old_material_type_id' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            [
                'id' => 500,
                'parent_id' => 490,
                'name' => 'Celadon',
                'concatenated_name' => 'Iron - Celadon',
                'rgb_r' => 143,
                'rgb_g' => 188,
                'rgb_b' => 143,
                'old_recipe_type_id' => 40,
                'old_material_type_id' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            [
                'id' => 510,
                'parent_id' => 500,
                'name' => 'Blue',
                'concatenated_name' => 'Iron - Celadon - Blue',
                'rgb_r' => 217,
                'rgb_g' => 217,
                'rgb_b' => 243,
                'old_recipe_type_id' => 41,
                'old_material_type_id' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            [
                'id' => 520,
                'parent_id' => 500,
                'name' => 'Green',
                'concatenated_name' => 'Iron - Celadon - Green',
                'rgb_r' => 143,
                'rgb_g' => 188,
                'rgb_b' => 143,
                'old_recipe_type_id' => 42,
                'old_material_type_id' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            [
                'id' => 530,
                'parent_id' => 500,
                'name' => 'Yellow',
                'concatenated_name' => 'Iron - Celadon - Yellow',
                'rgb_r' => 255,
                'rgb_g' => 215,
                'rgb_b' => 0,
                'old_recipe_type_id' => 43,
                'old_material_type_id' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            [
                'id' => 533,
                'parent_id' => 500,
                'name' => 'Chun, Jun',
                'concatenated_name' => 'Iron - Celadon - Chun',
                'rgb_r' => 255,
                'rgb_g' => 255,
                'rgb_b' => 255,
                'old_recipe_type_id' => 114,
                'old_material_type_id' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            [
                'id' => 535,
                'parent_id' => 490,
                'name' => 'Amber',
                'concatenated_name' => 'Iron - Amber',
                'rgb_r' => 255,
                'rgb_g' => 255,
                'rgb_b' => 255,
                'old_recipe_type_id' => 113,
                'old_material_type_id' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            [
                'id' => 540,
                'parent_id' => 490,
                'name' => 'Tenmoku, Temmoku, Tianmu',
                'concatenated_name' => 'Iron - Tenmoku',
                'rgb_r' => 30,
                'rgb_g' => 10,
                'rgb_b' => 0,
                'old_recipe_type_id' => 44,
                'old_material_type_id' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            [
                'id' => 550,
                'parent_id' => 490,
                'name' => 'Tea Dust',
                'concatenated_name' => 'Iron - Tea Dust',
                'rgb_r' => 128,
                'rgb_g' => 128,
                'rgb_b' => 61,
                'old_recipe_type_id' => 45,
                'old_material_type_id' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            [
                'id' => 560,
                'parent_id' => 490,
                'name' => 'Tessha, Hare\'s Fur',
                'concatenated_name' => 'Iron - Tessha, Hare\'s Fur',
                'rgb_r' => 20,
                'rgb_g' => 10,
                'rgb_b' => 10,
                'old_recipe_type_id' => 46,
                'old_material_type_id' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            [
                'id' => 570,
                'parent_id' => 490,
                'name' => 'Kaki, Tomato Red',
                'concatenated_name' => 'Iron - Kaki, Tomato Red',
                'rgb_r' => 205,
                'rgb_g' => 79,
                'rgb_b' => 57,
                'old_recipe_type_id' => 47,
                'old_material_type_id' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            [
                'id' => 580,
                'parent_id' => 490,
                'name' => 'Oil Spot',
                'concatenated_name' => 'Iron - Oil Spot',
                'rgb_r' => 255,
                'rgb_g' => 255,
                'rgb_b' => 255,
                'old_recipe_type_id' => 48,
                'old_material_type_id' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            [
                'id' => 585,
                'parent_id' => 490,
                'name' => 'Slip-Based',
                'concatenated_name' => 'Iron - Slip-Based',
                'rgb_r' => 255,
                'rgb_g' => 255,
                'rgb_b' => 255,
                'old_recipe_type_id' => 110,
                'old_material_type_id' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            [
                'id' => 590,
                'parent_id' => 460,
                'name' => 'Shino',
                'concatenated_name' => 'Shino',
                'rgb_r' => 255,
                'rgb_g' => 255,
                'rgb_b' => 255,
                'old_recipe_type_id' => 49,
                'old_material_type_id' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            [
                'id' => 600,
                'parent_id' => 590,
                'name' => 'Traditional',
                'concatenated_name' => 'Shino - Traditional',
                'rgb_r' => 255,
                'rgb_g' => 255,
                'rgb_b' => 255,
                'old_recipe_type_id' => 50,
                'old_material_type_id' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            [
                'id' => 610,
                'parent_id' => 590,
                'name' => 'Carbon Trap',
                'concatenated_name' => 'Shino - Carbon Trap',
                'rgb_r' => 255,
                'rgb_g' => 255,
                'rgb_b' => 255,
                'old_recipe_type_id' => 51,
                'old_material_type_id' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            [
                'id' => 620,
                'parent_id' => 590,
                'name' => 'High-Alumina',
                'concatenated_name' => 'Shino - High-Alumina',
                'rgb_r' => 255,
                'rgb_g' => 255,
                'rgb_b' => 255,
                'old_recipe_type_id' => 52,
                'old_material_type_id' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            [
                'id' => 630,
                'parent_id' => 590,
                'name' => 'White',
                'concatenated_name' => 'Shino - White',
                'rgb_r' => 255,
                'rgb_g' => 255,
                'rgb_b' => 255,
                'old_recipe_type_id' => 53,
                'old_material_type_id' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            [
                'id' => 635,
                'parent_id' => 460,
                'name' => 'Red',
                'concatenated_name' => 'Red',
                'rgb_r' => 190,
                'rgb_g' => 0,
                'rgb_b' => 0,
                'old_recipe_type_id' => 101,
                'old_material_type_id' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            [
                'id' => 640,
                'parent_id' => 635,
                'name' => 'Copper',
                'concatenated_name' => 'Red - Copper',
                'rgb_r' => 255,
                'rgb_g' => 255,
                'rgb_b' => 255,
                'old_recipe_type_id' => 54,
                'old_material_type_id' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            [
                'id' => 650,
                'parent_id' => 640,
                'name' => 'Oxblood',
                'concatenated_name' => 'Red - Copper - Oxblood',
                'rgb_r' => 255,
                'rgb_g' => 255,
                'rgb_b' => 255,
                'old_recipe_type_id' => 55,
                'old_material_type_id' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            [
                'id' => 660,
                'parent_id' => 640,
                'name' => 'Flambe',
                'concatenated_name' => 'Red - Copper - Flambe',
                'rgb_r' => 255,
                'rgb_g' => 255,
                'rgb_b' => 255,
                'old_recipe_type_id' => 56,
                'old_material_type_id' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            [
                'id' => 670,
                'parent_id' => 640,
                'name' => 'Peach Bloom',
                'concatenated_name' => 'Red - Copper - Peach Bloom',
                'rgb_r' => 255,
                'rgb_g' => 255,
                'rgb_b' => 255,
                'old_recipe_type_id' => 57,
                'old_material_type_id' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            [
                'id' => 673,
                'parent_id' => 635,
                'name' => 'Pink',
                'concatenated_name' => 'Red - Pink',
                'rgb_r' => 255,
                'rgb_g' => 255,
                'rgb_b' => 255,
                'old_recipe_type_id' => 112,
                'old_material_type_id' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            [
                'id' => 675,
                'parent_id' => 635,
                'name' => 'Stain',
                'concatenated_name' => 'Red - Stain',
                'rgb_r' => 255,
                'rgb_g' => 255,
                'rgb_b' => 255,
                'old_recipe_type_id' => 111,
                'old_material_type_id' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            [
                'id' => 680,
                'parent_id' => 460,
                'name' => 'Green',
                'concatenated_name' => 'Green',
                'rgb_r' => 0,
                'rgb_g' => 200,
                'rgb_b' => 0,
                'old_recipe_type_id' => 58,
                'old_material_type_id' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            [
                'id' => 690,
                'parent_id' => 680,
                'name' => 'Copper',
                'concatenated_name' => 'Green - Copper',
                'rgb_r' => 0,
                'rgb_g' => 200,
                'rgb_b' => 0,
                'old_recipe_type_id' => 59,
                'old_material_type_id' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            [
                'id' => 700,
                'parent_id' => 680,
                'name' => 'Oribe',
                'concatenated_name' => 'Green - Oribe',
                'rgb_r' => 0,
                'rgb_g' => 200,
                'rgb_b' => 0,
                'old_recipe_type_id' => 60,
                'old_material_type_id' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            [
                'id' => 710,
                'parent_id' => 680,
                'name' => 'Chrome',
                'concatenated_name' => 'Green - Chrome',
                'rgb_r' => 0,
                'rgb_g' => 200,
                'rgb_b' => 0,
                'old_recipe_type_id' => 61,
                'old_material_type_id' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            [
                'id' => 720,
                'parent_id' => 680,
                'name' => 'Titanium',
                'concatenated_name' => 'Green - Titanium',
                'rgb_r' => 0,
                'rgb_g' => 200,
                'rgb_b' => 0,
                'old_recipe_type_id' => 62,
                'old_material_type_id' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            [
                'id' => 730,
                'parent_id' => 680,
                'name' => 'Nickel',
                'concatenated_name' => 'Green - Nickel',
                'rgb_r' => 0,
                'rgb_g' => 200,
                'rgb_b' => 0,
                'old_recipe_type_id' => 63,
                'old_material_type_id' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            [
                'id' => 740,
                'parent_id' => 680,
                'name' => 'Stain',
                'concatenated_name' => 'Green - Stain',
                'rgb_r' => 0,
                'rgb_g' => 200,
                'rgb_b' => 0,
                'old_recipe_type_id' => 64,
                'old_material_type_id' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            [
                'id' => 745,
                'parent_id' => 460,
                'name' => 'Turquoise',
                'concatenated_name' => 'Turquoise',
                'rgb_r' => 255,
                'rgb_g' => 255,
                'rgb_b' => 255,
                'old_recipe_type_id' => 108,
                'old_material_type_id' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            [
                'id' => 750,
                'parent_id' => 460,
                'name' => 'Blue',
                'concatenated_name' => 'Blue',
                'rgb_r' => 0,
                'rgb_g' => 0,
                'rgb_b' => 200,
                'old_recipe_type_id' => 65,
                'old_material_type_id' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            [
                'id' => 760,
                'parent_id' => 750,
                'name' => 'Cobalt',
                'concatenated_name' => 'Blue - Cobalt',
                'rgb_r' => 0,
                'rgb_g' => 0,
                'rgb_b' => 200,
                'old_recipe_type_id' => 66,
                'old_material_type_id' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            [
                'id' => 770,
                'parent_id' => 750,
                'name' => 'Rutile',
                'concatenated_name' => 'Blue - Rutile',
                'rgb_r' => 0,
                'rgb_g' => 0,
                'rgb_b' => 200,
                'old_recipe_type_id' => 67,
                'old_material_type_id' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            [
                'id' => 780,
                'parent_id' => 750,
                'name' => 'Barium',
                'concatenated_name' => 'Blue - Barium',
                'rgb_r' => 0,
                'rgb_g' => 0,
                'rgb_b' => 200,
                'old_recipe_type_id' => 68,
                'old_material_type_id' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            [
                'id' => 790,
                'parent_id' => 750,
                'name' => 'Strontium',
                'concatenated_name' => 'Blue - Strontium',
                'rgb_r' => 0,
                'rgb_g' => 0,
                'rgb_b' => 200,
                'old_recipe_type_id' => 69,
                'old_material_type_id' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            [
                'id' => 800,
                'parent_id' => 750,
                'name' => 'Nickel',
                'concatenated_name' => 'Blue - Nickel',
                'rgb_r' => 0,
                'rgb_g' => 0,
                'rgb_b' => 200,
                'old_recipe_type_id' => 70,
                'old_material_type_id' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            [
                'id' => 810,
                'parent_id' => 750,
                'name' => 'Stain',
                'concatenated_name' => 'Blue - Stain',
                'rgb_r' => 0,
                'rgb_g' => 0,
                'rgb_b' => 200,
                'old_recipe_type_id' => 71,
                'old_material_type_id' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            [
                'id' => 820,
                'parent_id' => 460,
                'name' => 'Purple',
                'concatenated_name' => 'Purple',
                'rgb_r' => 93,
                'rgb_g' => 71,
                'rgb_b' => 139,
                'old_recipe_type_id' => 72,
                'old_material_type_id' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            [
                'id' => 830,
                'parent_id' => 820,
                'name' => 'Magnesium Matte',
                'concatenated_name' => 'Purple - Magnesium Matte',
                'rgb_r' => 93,
                'rgb_g' => 71,
                'rgb_b' => 139,
                'old_recipe_type_id' => 73,
                'old_material_type_id' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            [
                'id' => 840,
                'parent_id' => 820,
                'name' => 'Nickel',
                'concatenated_name' => 'Purple - Nickel',
                'rgb_r' => 93,
                'rgb_g' => 71,
                'rgb_b' => 139,
                'old_recipe_type_id' => 74,
                'old_material_type_id' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            [
                'id' => 850,
                'parent_id' => 820,
                'name' => 'Manganese',
                'concatenated_name' => 'Purple - Manganese',
                'rgb_r' => 93,
                'rgb_g' => 71,
                'rgb_b' => 139,
                'old_recipe_type_id' => 75,
                'old_material_type_id' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            [
                'id' => 860,
                'parent_id' => 460,
                'name' => 'Matte',
                'concatenated_name' => 'Matte',
                'rgb_r' => 255,
                'rgb_g' => 255,
                'rgb_b' => 255,
                'old_recipe_type_id' => 76,
                'old_material_type_id' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            [
                'id' => 870,
                'parent_id' => 860,
                'name' => 'Magnesium Matte',
                'concatenated_name' => 'Matte - Magnesium Matte',
                'rgb_r' => 255,
                'rgb_g' => 255,
                'rgb_b' => 255,
                'old_recipe_type_id' => 77,
                'old_material_type_id' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            [
                'id' => 880,
                'parent_id' => 460,
                'name' => 'Black',
                'concatenated_name' => 'Black',
                'rgb_r' => 10,
                'rgb_g' => 10,
                'rgb_b' => 10,
                'old_recipe_type_id' => 78,
                'old_material_type_id' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            [
                'id' => 890,
                'parent_id' => 880,
                'name' => 'Slip-Based',
                'concatenated_name' => 'Black - Slip-Based',
                'rgb_r' => 10,
                'rgb_g' => 10,
                'rgb_b' => 10,
                'old_recipe_type_id' => 79,
                'old_material_type_id' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            [
                'id' => 900,
                'parent_id' => 880,
                'name' => 'Glossy',
                'concatenated_name' => 'Black - Glossy',
                'rgb_r' => 10,
                'rgb_g' => 10,
                'rgb_b' => 10,
                'old_recipe_type_id' => 80,
                'old_material_type_id' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            [
                'id' => 910,
                'parent_id' => 880,
                'name' => 'Satin',
                'concatenated_name' => 'Black - Satin',
                'rgb_r' => 10,
                'rgb_g' => 10,
                'rgb_b' => 10,
                'old_recipe_type_id' => 81,
                'old_material_type_id' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            [
                'id' => 920,
                'parent_id' => 460,
                'name' => 'Yellow',
                'concatenated_name' => 'Yellow',
                'rgb_r' => 255,
                'rgb_g' => 215,
                'rgb_b' => 0,
                'old_recipe_type_id' => 82,
                'old_material_type_id' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            [
                'id' => 930,
                'parent_id' => 920,
                'name' => 'Iron',
                'concatenated_name' => 'Yellow - Iron',
                'rgb_r' => 255,
                'rgb_g' => 215,
                'rgb_b' => 0,
                'old_recipe_type_id' => 83,
                'old_material_type_id' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            [
                'id' => 940,
                'parent_id' => 920,
                'name' => 'Barium',
                'concatenated_name' => 'Yellow - Barium',
                'rgb_r' => 255,
                'rgb_g' => 215,
                'rgb_b' => 0,
                'old_recipe_type_id' => 84,
                'old_material_type_id' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            [
                'id' => 950,
                'parent_id' => 920,
                'name' => 'Manganese',
                'concatenated_name' => 'Yellow - Manganese',
                'rgb_r' => 255,
                'rgb_g' => 215,
                'rgb_b' => 0,
                'old_recipe_type_id' => 85,
                'old_material_type_id' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            [
                'id' => 960,
                'parent_id' => 920,
                'name' => 'Stain',
                'concatenated_name' => 'Yellow - Stain',
                'rgb_r' => 255,
                'rgb_g' => 215,
                'rgb_b' => 0,
                'old_recipe_type_id' => 86,
                'old_material_type_id' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            [
                'id' => 970,
                'parent_id' => 920,
                'name' => 'Nickel',
                'concatenated_name' => 'Yellow - Nickel',
                'rgb_r' => 255,
                'rgb_g' => 215,
                'rgb_b' => 0,
                'old_recipe_type_id' => 87,
                'old_material_type_id' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            [
                'id' => 980,
                'parent_id' => 460,
                'name' => 'Crystalline',
                'concatenated_name' => 'Crystalline',
                'rgb_r' => 255,
                'rgb_g' => 255,
                'rgb_b' => 255,
                'old_recipe_type_id' => 88,
                'old_material_type_id' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            [
                'id' => 990,
                'parent_id' => 980,
                'name' => 'Micro',
                'concatenated_name' => 'Crystalline - Micro',
                'rgb_r' => 255,
                'rgb_g' => 255,
                'rgb_b' => 255,
                'old_recipe_type_id' => 89,
                'old_material_type_id' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            [
                'id' => 1000,
                'parent_id' => 980,
                'name' => 'Aventurine',
                'concatenated_name' => 'Crystalline - Aventurine',
                'rgb_r' => 255,
                'rgb_g' => 255,
                'rgb_b' => 255,
                'old_recipe_type_id' => 90,
                'old_material_type_id' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            [
                'id' => 1010,
                'parent_id' => 980,
                'name' => 'Manganese',
                'concatenated_name' => 'Crystalline - Manganese',
                'rgb_r' => 255,
                'rgb_g' => 255,
                'rgb_b' => 255,
                'old_recipe_type_id' => 91,
                'old_material_type_id' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            [
                'id' => 1020,
                'parent_id' => 980,
                'name' => 'Macro',
                'concatenated_name' => 'Crystalline - Macro',
                'rgb_r' => 255,
                'rgb_g' => 255,
                'rgb_b' => 255,
                'old_recipe_type_id' => 92,
                'old_material_type_id' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            [
                'id' => 1030,
                'parent_id' => 460,
                'name' => 'Single-Fire',
                'concatenated_name' => 'Single-Fire',
                'rgb_r' => 255,
                'rgb_g' => 255,
                'rgb_b' => 255,
                'old_recipe_type_id' => 93,
                'old_material_type_id' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            [
                'id' => 1040,
                'parent_id' => 460,
                'name' => 'Wood',
                'concatenated_name' => 'Wood',
                'rgb_r' => 255,
                'rgb_g' => 255,
                'rgb_b' => 255,
                'old_recipe_type_id' => 94,
                'old_material_type_id' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            [
                'id' => 1050,
                'parent_id' => 460,
                'name' => 'Salt & Soda',
                'concatenated_name' => 'Salt & Soda',
                'rgb_r' => 255,
                'rgb_g' => 255,
                'rgb_b' => 255,
                'old_recipe_type_id' => 95,
                'old_material_type_id' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            [
                'id' => 1055,
                'parent_id' => 460,
                'name' => 'Raku',
                'concatenated_name' => 'Raku',
                'rgb_r' => 255,
                'rgb_g' => 255,
                'rgb_b' => 255,
                'old_recipe_type_id' => 109,
                'old_material_type_id' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            [
                'id' => 1060,
                'parent_id' => 460,
                'name' => 'Ash',
                'concatenated_name' => 'Ash',
                'rgb_r' => 255,
                'rgb_g' => 255,
                'rgb_b' => 255,
                'old_recipe_type_id' => 96,
                'old_material_type_id' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            [
                'id' => 1070,
                'parent_id' => 1060,
                'name' => 'Nuka',
                'concatenated_name' => 'Ash - Nuka',
                'rgb_r' => 255,
                'rgb_g' => 255,
                'rgb_b' => 255,
                'old_recipe_type_id' => 97,
                'old_material_type_id' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            [
                'id' => 1080,
                'parent_id' => 1060,
                'name' => 'Synthetic/Fake',
                'concatenated_name' => 'Ash - Synthetic/Fake',
                'rgb_r' => 255,
                'rgb_g' => 255,
                'rgb_b' => 255,
                'old_recipe_type_id' => 98,
                'old_material_type_id' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            [
                'id' => 1090,
                'parent_id' => 1060,
                'name' => 'Slip-Based',
                'concatenated_name' => 'Ash - Slip-Based',
                'rgb_r' => 255,
                'rgb_g' => 255,
                'rgb_b' => 255,
                'old_recipe_type_id' => 99,
                'old_material_type_id' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            [
                'id' => 1100,
                'parent_id' => 460,
                'name' => 'Majolica',
                'concatenated_name' => 'Majolica',
                'rgb_r' => 255,
                'rgb_g' => 255,
                'rgb_b' => 255,
                'old_recipe_type_id' => 100,
                'old_material_type_id' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            [
                'id' => 1130,
                'parent_id' => 460,
                'name' => 'Specialty',
                'concatenated_name' => 'Specialty',
                'rgb_r' => 255,
                'rgb_g' => 255,
                'rgb_b' => 255,
                'old_recipe_type_id' => 103,
                'old_material_type_id' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            [
                'id' => 1140,
                'parent_id' => 1130,
                'name' => 'Crackle',
                'concatenated_name' => 'Specialty - Crackle',
                'rgb_r' => 255,
                'rgb_g' => 255,
                'rgb_b' => 255,
                'old_recipe_type_id' => 104,
                'old_material_type_id' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            [
                'id' => 1150,
                'parent_id' => 1130,
                'name' => 'Crawling',
                'concatenated_name' => 'Specialty - Crawling',
                'rgb_r' => 255,
                'rgb_g' => 255,
                'rgb_b' => 255,
                'old_recipe_type_id' => 105,
                'old_material_type_id' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            [
                'id' => 1160,
                'parent_id' => 1130,
                'name' => 'Crater',
                'concatenated_name' => 'Specialty - Crater',
                'rgb_r' => 255,
                'rgb_g' => 255,
                'rgb_b' => 255,
                'old_recipe_type_id' => 106,
                'old_material_type_id' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            [
                'id' => 1170,
                'parent_id' => 1130,
                'name' => 'Metallic',
                'concatenated_name' => 'Specialty - Metallic',
                'rgb_r' => 255,
                'rgb_g' => 255,
                'rgb_b' => 255,
                'old_recipe_type_id' => 107,
                'old_material_type_id' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            [
                'id' => 1180,
                'parent_id' => 100,
                'name' => 'Refractory',
                'concatenated_name' => 'Refractory',
                'rgb_r' => 255,
                'rgb_g' => 255,
                'rgb_b' => 255,
                'old_recipe_type_id' => 102,
                'old_material_type_id' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],

        ];

        DB::table('material_types')->insert($material_types);

        if (DB::connection()->getDriverName() == 'mysql') {
            DB::statement('SET FOREIGN_KEY_CHECKS=1;');
        }

    }
}
