
LOCK TABLES `countries` WRITE;
/*!40000 ALTER TABLE `countries` DISABLE KEYS */;

INSERT INTO `countries` (`id`, `name`, `code`, `deleted_at`)
VALUES
	(1,'Andorra','AD',NULL),
	(2,'United Arab Emirates','AE',NULL),
	(3,'Afghanistan','AF',NULL),
	(4,'Antigua and Barbuda','AG',NULL),
	(5,'Anguilla','AI',NULL),
	(6,'Albania','AL',NULL),
	(7,'Armenia','AM',NULL),
	(8,'Angola','AO',NULL),
	(9,'Antarctica','AQ',NULL),
	(10,'Argentina','AR',NULL),
	(11,'American Samoa','AS',NULL),
	(12,'Austria','AT',NULL),
	(13,'Australia','AU',NULL),
	(14,'Aruba','AW',NULL),
	(15,'Åland','AX',NULL),
	(16,'Azerbaijan','AZ',NULL),
	(17,'Bosnia and Herzegovina','BA',NULL),
	(18,'Barbados','BB',NULL),
	(19,'Bangladesh','BD',NULL),
	(20,'Belgium','BE',NULL),
	(21,'Burkina Faso','BF',NULL),
	(22,'Bulgaria','BG',NULL),
	(23,'Bahrain','BH',NULL),
	(24,'Burundi','BI',NULL),
	(25,'Benin','BJ',NULL),
	(26,'Saint Barthélemy','BL',NULL),
	(27,'Bermuda','BM',NULL),
	(28,'Brunei','BN',NULL),
	(29,'Bolivia','BO',NULL),
	(30,'Bonaire','BQ',NULL),
	(31,'Brazil','BR',NULL),
	(32,'Bahamas','BS',NULL),
	(33,'Bhutan','BT',NULL),
	(34,'Bouvet Island','BV',NULL),
	(35,'Botswana','BW',NULL),
	(36,'Belarus','BY',NULL),
	(37,'Belize','BZ',NULL),
	(38,'Canada','CA',NULL),
	(39,'Cocos [Keeling] Islands','CC',NULL),
	(40,'Democratic Republic of the Congo','CD',NULL),
	(41,'Central African Republic','CF',NULL),
	(42,'Republic of the Congo','CG',NULL),
	(43,'Switzerland','CH',NULL),
	(44,'Ivory Coast','CI',NULL),
	(45,'Cook Islands','CK',NULL),
	(46,'Chile','CL',NULL),
	(47,'Cameroon','CM',NULL),
	(48,'China','CN',NULL),
	(49,'Colombia','CO',NULL),
	(50,'Costa Rica','CR',NULL),
	(51,'Cuba','CU',NULL),
	(52,'Cape Verde','CV',NULL),
	(53,'Curacao','CW',NULL),
	(54,'Christmas Island','CX',NULL),
	(55,'Cyprus','CY',NULL),
	(56,'Czechia','CZ',NULL),
	(57,'Germany','DE',NULL),
	(58,'Djibouti','DJ',NULL),
	(59,'Denmark','DK',NULL),
	(60,'Dominica','DM',NULL),
	(61,'Dominican Republic','DO',NULL),
	(62,'Algeria','DZ',NULL),
	(63,'Ecuador','EC',NULL),
	(64,'Estonia','EE',NULL),
	(65,'Egypt','EG',NULL),
	(66,'Western Sahara','EH',NULL),
	(67,'Eritrea','ER',NULL),
	(68,'Spain','ES',NULL),
	(69,'Ethiopia','ET',NULL),
	(70,'Finland','FI',NULL),
	(71,'Fiji','FJ',NULL),
	(72,'Falkland Islands','FK',NULL),
	(73,'Micronesia','FM',NULL),
	(74,'Faroe Islands','FO',NULL),
	(75,'France','FR',NULL),
	(76,'Gabon','GA',NULL),
	(77,'United Kingdom','GB',NULL),
	(78,'Grenada','GD',NULL),
	(79,'Georgia','GE',NULL),
	(80,'French Guiana','GF',NULL),
	(81,'Guernsey','GG',NULL),
	(82,'Ghana','GH',NULL),
	(83,'Gibraltar','GI',NULL),
	(84,'Greenland','GL',NULL),
	(85,'Gambia','GM',NULL),
	(86,'Guinea','GN',NULL),
	(87,'Guadeloupe','GP',NULL),
	(88,'Equatorial Guinea','GQ',NULL),
	(89,'Greece','GR',NULL),
	(90,'South Georgia and the South Sandwich Islands','GS',NULL),
	(91,'Guatemala','GT',NULL),
	(92,'Guam','GU',NULL),
	(93,'Guinea-Bissau','GW',NULL),
	(94,'Guyana','GY',NULL),
	(95,'Hong Kong','HK',NULL),
	(96,'Heard Island and McDonald Islands','HM',NULL),
	(97,'Honduras','HN',NULL),
	(98,'Croatia','HR',NULL),
	(99,'Haiti','HT',NULL),
	(100,'Hungary','HU',NULL),
	(101,'Indonesia','ID',NULL),
	(102,'Ireland','IE',NULL),
	(103,'Israel','IL',NULL),
	(104,'Isle of Man','IM',NULL),
	(105,'India','IN',NULL),
	(106,'British Indian Ocean Territory','IO',NULL),
	(107,'Iraq','IQ',NULL),
	(108,'Iran','IR',NULL),
	(109,'Iceland','IS',NULL),
	(110,'Italy','IT',NULL),
	(111,'Jersey','JE',NULL),
	(112,'Jamaica','JM',NULL),
	(113,'Jordan','JO',NULL),
	(114,'Japan','JP',NULL),
	(115,'Kenya','KE',NULL),
	(116,'Kyrgyzstan','KG',NULL),
	(117,'Cambodia','KH',NULL),
	(118,'Kiribati','KI',NULL),
	(119,'Comoros','KM',NULL),
	(120,'Saint Kitts and Nevis','KN',NULL),
	(121,'North Korea','KP',NULL),
	(122,'South Korea','KR',NULL),
	(123,'Kuwait','KW',NULL),
	(124,'Cayman Islands','KY',NULL),
	(125,'Kazakhstan','KZ',NULL),
	(126,'Laos','LA',NULL),
	(127,'Lebanon','LB',NULL),
	(128,'Saint Lucia','LC',NULL),
	(129,'Liechtenstein','LI',NULL),
	(130,'Sri Lanka','LK',NULL),
	(131,'Liberia','LR',NULL),
	(132,'Lesotho','LS',NULL),
	(133,'Lithuania','LT',NULL),
	(134,'Luxembourg','LU',NULL),
	(135,'Latvia','LV',NULL),
	(136,'Libya','LY',NULL),
	(137,'Morocco','MA',NULL),
	(138,'Monaco','MC',NULL),
	(139,'Moldova','MD',NULL),
	(140,'Montenegro','ME',NULL),
	(141,'Saint Martin','MF',NULL),
	(142,'Madagascar','MG',NULL),
	(143,'Marshall Islands','MH',NULL),
	(144,'Macedonia','MK',NULL),
	(145,'Mali','ML',NULL),
	(146,'Myanmar [Burma]','MM',NULL),
	(147,'Mongolia','MN',NULL),
	(148,'Macao','MO',NULL),
	(149,'Northern Mariana Islands','MP',NULL),
	(150,'Martinique','MQ',NULL),
	(151,'Mauritania','MR',NULL),
	(152,'Montserrat','MS',NULL),
	(153,'Malta','MT',NULL),
	(154,'Mauritius','MU',NULL),
	(155,'Maldives','MV',NULL),
	(156,'Malawi','MW',NULL),
	(157,'Mexico','MX',NULL),
	(158,'Malaysia','MY',NULL),
	(159,'Mozambique','MZ',NULL),
	(160,'Namibia','NA',NULL),
	(161,'New Caledonia','NC',NULL),
	(162,'Niger','NE',NULL),
	(163,'Norfolk Island','NF',NULL),
	(164,'Nigeria','NG',NULL),
	(165,'Nicaragua','NI',NULL),
	(166,'Netherlands','NL',NULL),
	(167,'Norway','NO',NULL),
	(168,'Nepal','NP',NULL),
	(169,'Nauru','NR',NULL),
	(170,'Niue','NU',NULL),
	(171,'New Zealand','NZ',NULL),
	(172,'Oman','OM',NULL),
	(173,'Panama','PA',NULL),
	(174,'Peru','PE',NULL),
	(175,'French Polynesia','PF',NULL),
	(176,'Papua New Guinea','PG',NULL),
	(177,'Philippines','PH',NULL),
	(178,'Pakistan','PK',NULL),
	(179,'Poland','PL',NULL),
	(180,'Saint Pierre and Miquelon','PM',NULL),
	(181,'Pitcairn Islands','PN',NULL),
	(182,'Puerto Rico','PR',NULL),
	(183,'Palestine','PS',NULL),
	(184,'Portugal','PT',NULL),
	(185,'Palau','PW',NULL),
	(186,'Paraguay','PY',NULL),
	(187,'Qatar','QA',NULL),
	(188,'Réunion','RE',NULL),
	(189,'Romania','RO',NULL),
	(190,'Serbia','RS',NULL),
	(191,'Russia','RU',NULL),
	(192,'Rwanda','RW',NULL),
	(193,'Saudi Arabia','SA',NULL),
	(194,'Solomon Islands','SB',NULL),
	(195,'Seychelles','SC',NULL),
	(196,'Sudan','SD',NULL),
	(197,'Sweden','SE',NULL),
	(198,'Singapore','SG',NULL),
	(199,'Saint Helena','SH',NULL),
	(200,'Slovenia','SI',NULL),
	(201,'Svalbard and Jan Mayen','SJ',NULL),
	(202,'Slovakia','SK',NULL),
	(203,'Sierra Leone','SL',NULL),
	(204,'San Marino','SM',NULL),
	(205,'Senegal','SN',NULL),
	(206,'Somalia','SO',NULL),
	(207,'Suriname','SR',NULL),
	(208,'South Sudan','SS',NULL),
	(209,'São Tomé and Príncipe','ST',NULL),
	(210,'El Salvador','SV',NULL),
	(211,'Sint Maarten','SX',NULL),
	(212,'Syria','SY',NULL),
	(213,'Swaziland','SZ',NULL),
	(214,'Turks and Caicos Islands','TC',NULL),
	(215,'Chad','TD',NULL),
	(216,'French Southern Territories','TF',NULL),
	(217,'Togo','TG',NULL),
	(218,'Thailand','TH',NULL),
	(219,'Tajikistan','TJ',NULL),
	(220,'Tokelau','TK',NULL),
	(221,'East Timor','TL',NULL),
	(222,'Turkmenistan','TM',NULL),
	(223,'Tunisia','TN',NULL),
	(224,'Tonga','TO',NULL),
	(225,'Turkey','TR',NULL),
	(226,'Trinidad and Tobago','TT',NULL),
	(227,'Tuvalu','TV',NULL),
	(228,'Taiwan','TW',NULL),
	(229,'Tanzania','TZ',NULL),
	(230,'Ukraine','UA',NULL),
	(231,'Uganda','UG',NULL),
	(232,'U.S. Minor Outlying Islands','UM',NULL),
	(233,'United States','US',NULL),
	(234,'Uruguay','UY',NULL),
	(235,'Uzbekistan','UZ',NULL),
	(236,'Vatican City','VA',NULL),
	(237,'Saint Vincent and the Grenadines','VC',NULL),
	(238,'Venezuela','VE',NULL),
	(239,'British Virgin Islands','VG',NULL),
	(240,'U.S. Virgin Islands','VI',NULL),
	(241,'Vietnam','VN',NULL),
	(242,'Vanuatu','VU',NULL),
	(243,'Wallis and Futuna','WF',NULL),
	(244,'Samoa','WS',NULL),
	(245,'Kosovo','XK',NULL),
	(246,'Yemen','YE',NULL),
	(247,'Mayotte','YT',NULL),
	(248,'South Africa','ZA',NULL),
	(249,'Zambia','ZM',NULL),
	(250,'Zimbabwe','ZW',NULL);

/*!40000 ALTER TABLE `countries` ENABLE KEYS */;
UNLOCK TABLES;
